26 learning process service
Relorer/Edokuri pull request #46
Opened 2023-03-22 20:34 UTC by Chursyatina

2023-03-22 20:36 UTC, Chursyatina commented
learn_controller у меня здесь make format убирает инициализацию со скрина, без неё работать не будет, если вынести её в конструктор контроллера то тоже работать не будет
![image](https://user-images.githubusercontent.com/60659856/227031798-78a22620-3966-47b4-8f63-b07ce818763a.png)

2023-03-24 06:18 UTC, Relorer requested changes

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/learn_controller.dart
> +  }
дублирование кода

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/review_intervals.dart
> +}
этого метода не должно быть, он не укладывается в новую парадигму, где интервал зависит не от количества ревью а он состояний и шагов

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/review_intervals.dart
> +
абстрактное название с магическими числами, умножение зависит от шага и состояния и должно определятся в состоянии или шаге а не сводится к свичу, свичей быть не должно вообще не считая сериалайзеров

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/review_intervals.dart
> +}
в целом может переехать в record, чтобы не осталять его тут одного

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/entities/record.dart
> +  }
бизнес логики в моделях быть не должно

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordState/stateSerializer.dart
> +  }
return RecordState.values.firstWhere((e) => e.toString() == 'RecordState.' + state);

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordState/stateSerializer.dart
> +  }
return getRecordStateString(state);

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordState/stateSerializer.dart
> +  }
удаляем getRecordStateString
и return state.toString().split('.').last;

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordStep/foursStep.dart
> +    return interval;
заведи глобальные константы для дня и года

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordStep/foursStep.dart
> +    return interval;
мы не хотим ограничивать интервал на одном году

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordStep/foursStep.dart
> +              : 0);
ебать

2023-03-24 06:18 UTC, Relorer commented on lib/src/models/recordStep/secondStep.dart
> +}
почти все можно вынести в абстрактный клас, наследники отличаются только коэфициентами насколько я понимаю

2023-03-24 06:18 UTC, Relorer commented on lib/src/pages/learn_page/learn_page_answer_buttons_menu.dart
> +      required this.markRecordAgain});
убираем, мы mobx используем не для красоты
читаешь из контекста свой контроллер который передал через провайдер и используешь методы 
context.read<LearnContorller>().blabla()

2023-03-24 06:18 UTC, Relorer commented on lib/src/pages/learn_page/learn_page_answer_buttons_menu.dart
> +            markRecordGood!(),
бизнес логика в ui, 
onTap: context.read<LearnController>().markRecordGood,

2023-03-24 06:18 UTC, Relorer commented on lib/src/pages/reader/widgets/reader_content_view_page/saved_word.dart
> +    int year = 65 * 24 * 60 * 60 * 1000;
какой то странный год

2023-03-24 06:18 UTC, Relorer commented on lib/src/pages/reader/widgets/reader_content_view_page/saved_word.dart
> +    if (reviewInterval != 0) {}
?

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/learn_controller.dart
> +  late Record? currentRecord = null;
null не инициализируют
а ошибка скорее всего из за late

2023-03-26 17:43 UTC, Relorer requested changes

2023-03-26 17:43 UTC, Relorer commented on lib/src/pages/reader/widgets/reader_content_view_page/saved_word.dart
> +          reviewInterval)), // .withOpacity(0.4 * ((7 - min(reviewNumber, 7)) / 7)),
убрать коментарий
параметр передается но не используется потому что он не нужен

2023-03-26 17:43 UTC, Relorer commented on lib/src/pages/learn_page/learn_page.dart
> +    if (learnController.answerIsShown && record.meanings.isNotEmpty) {
лучше learnController.answerIsShown передать как параметр, выглядит так будто работать не должно а если работает то как второстепенный эффект

2023-03-26 17:43 UTC, Relorer commented on lib/src/models/recordStep/firstStep.dart
> +class FirstStep extends RecordStep {
Переименуй в RecordStep1 RecordStep2... а то сортировка слетает неудобно

2023-03-26 17:43 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/words_markers.dart
> +}
и с какой целью это лежит в отдельном файле не привязано не к какому типу, когда это явно кусок learn контроллера

2023-03-26 17:43 UTC, Relorer commented on lib/src/models/entities/record.dart
> +
эта штука используется в одном месте туда ее и перенести

2023-03-26 17:43 UTC, Relorer commented on lib/src/models/recordStep/recordStep.dart
> +  }
какая то хуйня, половина наследников использует половина нет, тут должно быть только то что подходит всем

2023-03-26 17:43 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/words_markers.dart
> +  record.reviewNumber++;
зачем увеличивать ревьюнамбер тут если мы все равно вызываетм метод шага

2023-03-26 17:43 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/learn_controller.dart
> +    }
странные маневры с индексами
мы можем удалять из списка не только по индексу но и по значению
а еслибы у нас был только id то можно было бы делать что то подобное 
books.removeWhere((element) => element.id == record.id);
но явно не такие махинации трехэтажные

2023-03-26 17:43 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/learn_controller.dart
> +    }
тут безопасней и читаемей использовать свичи

2023-03-26 17:43 UTC, Relorer commented on lib/src/controllers/stores/learn_controller/learn_controller.dart
> +      }
читаемей и безопасней 3 линка 
recent = _records.Wherer(r => r.recordState == RecordState.recent).toList()
и эти 3 строки можно просто в конструкторе оставить без метода

2023-03-26 19:20 UTC, Relorer requested changes

2023-03-26 19:20 UTC, Relorer commented on lib/src/models/recordStep/recordStep.dart
> +}
заменить на интерфейс

2023-03-27 20:16 UTC, merged