Custom cover adding implemented
Relorer/Edokuri pull request #49
Opened 2023-03-23 19:34 UTC by TheFRR

![image](https://user-images.githubusercontent.com/52603467/227330345-1aa7cc7e-26e4-4747-9670-d32f8e0fa753.png)
![image](https://user-images.githubusercontent.com/52603467/227330452-33b36d35-6c15-42c0-bd92-36fe7a0c5d49.png)

2023-03-24 06:18 UTC, Relorer requested changes

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/repositories/book_repository/book_repository.dart
> +        )
возможно не имеет смысла отправлять все файлы для обновления, должно быть достаточно только обложки

2023-03-24 06:18 UTC, Relorer commented on lib/src/controllers/stores/repositories/book_repository/book_repository.dart
> +  void updateBookCover(Book book) async {
должен возвращать future

2023-03-24 06:18 UTC, Relorer commented on lib/src/pages/home_page/screens/library_screen/widgets/book_card/book_card.dart
> +    getIt<BookRepository>().updateBookCover(book);
не эвэйтим обновление

2023-03-24 08:30 UTC, merged

2026-09-23 15:46 UTC, yacoubadanioko867-netizen approved these changes